Fixed STEAMID to STEAM_ID

diff --git a/containers/steamcmd/init/02_game_server b/containers/steamcmd/init/02_game_server
--- a/containers/steamcmd/init/02_game_server
+++ b/containers/steamcmd/init/02_game_server
@@ -5,6 +5,10 @@ if [ -z "$STEAM_USER" ]; then
 fi
 cd $STEAMCMD_PATH
 echo " [i] STEAM USER [$STEAM_USER]"
-echo " [i] STEAM GAME SERVER ID [$STEAMID]"
+echo " [i] STEAM GAME SERVER ID [$STEAM_ID]"
+if [ -z "$STEAM_ID" ]; then
+    echo " [x] SERVER [UPDATING] ERROR - STEAM_ID not provided."
+    exit 1
+fi
 echo " [*] SERVER [UPDATING]"
-./steamcmd.sh +force_install_dir $INSTALL_DIR +login $STEAM_USER $STEAM_PASSWORD +app_update $STEAMID validate +quit
+./steamcmd.sh +force_install_dir $INSTALL_DIR +login $STEAM_USER $STEAM_PASSWORD +app_update $STEAM_ID validate +quit
