Renamed files

diff --git a/containers/steamcmd/init/entrypoint b/containers/steamcmd/init/entrypoint
--- a/containers/steamcmd/init/entrypoint
+++ b/containers/steamcmd/init/entrypoint
@@ -1,9 +1,16 @@
 #!/bin/bash
+
+while true
+do
+    echo "tiktok"
+    sleep 1
+done
+
 state_file="/home/steam/peon/state"
 ip_file="/home/steam/peon/ip"
 #echo -e "\e[32mword\e[0m"
 echo "###################################################"
-echo -e "##### Starting e[32PEON\e[0m SteamCMD server v$VERSION"
+echo -e "##### Starting PEON SteamCMD server v$VERSION"
 echo "##### $(date)"
 echo "###################################################"
 echo "##### Initialisation [START]"
@@ -11,7 +18,7 @@ echo "##### Initialisation [START]"
 echo -n "BOOTING" > $state_file
 echo "0.0.0.0" > $ip_file
 # RUN STANDARD SCRIPT
-/init/init.sh && echo "PEON INIT - COMPLETE" || { echo "PEON INIT - FAILED"; exit 1; }
+/init/init && echo "PEON INIT - COMPLETE" || { echo "PEON INIT - FAILED"; exit 1; }
 # RUN CUSTOM INIT, IF FOUND
 if [ -e "/init/init_custom" ]
 then
@@ -27,6 +34,6 @@ then
     /init/server_start
 else
     echo -n "ERROR.MISSING_START_SCRIPT" > $state_file
-    echo " ERROR /init/server_start.sh not found. Did you forget to configure the mount for it?"
+    echo " ERROR /init/server_start not found. Did you forget to configure the mount for it?"
 fi
 echo "##### Server [END]"
